name: CI

on:
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.vscode/settings.json'
      - '.editorconfig'
      - 'CONTRIBUTING.md'
      - 'README.md'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Disable telemetry message
  DOTNET_NOLOGO: true
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Do not extract XML documentation files from nuget packages
  NUGET_XMLDOC_MODE: skip
  PROJECT_CONFIGURATION: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name : dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build --configuration ${{ env.PROJECT_CONFIGURATION }} --no-restore
